name: Python Workflow

on:
  push:
    branches:
      - main  # Adjust this branch name if needed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' 

    - name: Run all tests
      run: python -m unittest discover tests
